# Generated by Django 6.0.2 on 2026-03-03 21:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='experience_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['is_active'], name='jobs_job_is_acti_b6ae73_idx'),
        ),
    ]
